# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/vladimir/TESTDIFFAC/cernv1/cernv1.srcs/sources_1/ip/v6_sfifo_15x128/v6_sfifo_15x128.xci
# IP: The module: 'v6_sfifo_15x128' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vladimir/TESTDIFFAC/cernv1/cernv1.srcs/sources_1/ip/v6_sfifo_15x128/v6_sfifo_15x128/v6_sfifo_15x128.xdc
# XDC: The top module name and the constraint reference have the same name: 'v6_sfifo_15x128'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/vladimir/TESTDIFFAC/cernv1/cernv1.srcs/sources_1/ip/v6_sfifo_15x128/v6_sfifo_15x128_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'v6_sfifo_15x128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/vladimir/TESTDIFFAC/cernv1/cernv1.srcs/sources_1/ip/v6_sfifo_15x128/v6_sfifo_15x128.xci
# IP: The module: 'v6_sfifo_15x128' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vladimir/TESTDIFFAC/cernv1/cernv1.srcs/sources_1/ip/v6_sfifo_15x128/v6_sfifo_15x128/v6_sfifo_15x128.xdc
# XDC: The top module name and the constraint reference have the same name: 'v6_sfifo_15x128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/vladimir/TESTDIFFAC/cernv1/cernv1.srcs/sources_1/ip/v6_sfifo_15x128/v6_sfifo_15x128_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'v6_sfifo_15x128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
