# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

set_property BUFFER_TYPE NONE -quiet [get_ports -quiet -of [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0}]]
set_property BUFFER_TYPE NONE -quiet [get_ports -quiet -of [get_cells -hier -filter {REF_NAME==pcie_7x_0 || ORIG_REF_NAME==pcie_7x_0}]]
set_property BUFFER_TYPE NONE -quiet [get_ports -quiet -of [get_cells -hier -filter {REF_NAME==v6_sfifo_15x128 || ORIG_REF_NAME==v6_sfifo_15x128}]]
set_property BUFFER_TYPE NONE -quiet [get_ports -quiet -of [get_cells -hier -filter {REF_NAME==v6_mBuf_128x72 || ORIG_REF_NAME==v6_mBuf_128x72}]]
set_property BUFFER_TYPE NONE -quiet [get_ports -quiet -of [get_cells -hier -filter {REF_NAME==v6_eb_fifo_counted_resized || ORIG_REF_NAME==v6_eb_fifo_counted_resized}]]
