
####################################################################################
# Generated by PlanAhead 14.7 built on 'Fri Sep 27 19:24:36 MDT 2013' by 'xbuild'
####################################################################################


####################################################################################
# Constraints from file : 'ABB3_pcie_4_lane_Emu_FIFO_elink.ucf'
####################################################################################

##-----------------------------------------------------------------------------
##
## (c) Copyright 2010-2011 Xilinx, Inc. All rights reserved.
##
## This file contains confidential and proprietary information
## of Xilinx, Inc. and is protected under U.S. and
## international copyright and other intellectual property
## laws.
##
## DISCLAIMER
## This disclaimer is not a license and does not grant any
## rights to the materials distributed herewith. Except as
## otherwise provided in a valid license issued to you by
## Xilinx, and to the maximum extent permitted by applicable
## law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
## WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
## AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
## BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
## INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
## (2) Xilinx shall not be liable (whether in contract or tort,
## including negligence, or under any other theory of
## liability) for any loss or damage of any kind or nature
## related to, arising under or in connection with these
## materials, including for any direct, or any indirect,
## special, incidental, or consequential loss or damage
## (including loss of data, profits, goodwill, or any type of
## loss or damage suffered as a result of any action brought
## by a third party) even if such damage or loss was
## reasonably foreseeable or Xilinx had been advised of the
## possibility of the same.
##
## CRITICAL APPLICATIONS
## Xilinx products are not designed or intended to be fail-
## safe, or for use in any application requiring fail-safe
## performance, such as life-support or safety devices or
## systems, Class III medical devices, nuclear facilities,
## applications related to the deployment of airbags, or any
## other applications that could lead to death, personal
## injury, or severe property or environmental damage
## (individually and collectively, "Critical
## Applications"). Customer assumes the sole risk and
## liability of any use of Xilinx products in Critical
## Applications, subject only to applicable laws and
## regulations governing limitations on product liability.
##
## THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
## PART OF THIS FILE AT ALL TIMES.
##
##-----------------------------------------------------------------------------
## Project    : Series-7 Integrated Block for PCI Express
## File       : xilinx_pcie_2_1_ep_7x_04_lane_gen2_xc7a200t-fbg676-2_AC701.ucf
## Version    : 1.11

###############################################################################
# Define Device, Package And Speed Grade
###############################################################################


###############################################################################
# Pinout and Related I/O Constraints
###############################################################################
# Leds

set_property LOC AA19 [get_ports {leds[0]}]
set_property LOC AB20 [get_ports {leds[1]}]
set_property LOC AA21 [get_ports {leds[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[2]}]

# strobe soa

set_property PACKAGE_PIN AB21 [get_ports real_strobe_signal]
set_property PACKAGE_PIN AB22 [get_ports real_soa_signal]
set_property IOSTANDARD LVCMOS33 [get_ports real_soa_signal]
set_property IOSTANDARD LVCMOS33 [get_ports real_strobe_signal]
#
# SYS reset (input) signal.  The sys_reset_n signal should be
# obtained from the PCI Express interface if possible.  For
# slot based form factors, a system reset signal is usually
# present on the connector.  For cable based form factors, a
# system reset signal may not be available.  In this case, the
# system reset signal must be generated locally by some form of
# supervisory circuit.  You may change the IOSTANDARD and LOC
# to suit your requirements and VCCO voltage banking rules.
# Some 7 series devices do not have 3.3 V I/Os available.
# Therefore the appropriate level shift is required to operate
# with these devices that contain only 1.8 V banks.
#

set_property IOSTANDARD LVCMOS33 [get_ports sys_reset_n]

set_property PULLUP true [get_ports sys_reset_n]

set_property LOC AA20 [get_ports sys_reset_n]

set_false_path -from [get_ports sys_reset_n]

# SYS clock 100 MHz (input) signal. The sys_clk_p and sys_clk_n
# signals are the PCI Express reference clock. Virtex-7 GT
# Transceiver architecture requires the use of a dedicated clock
# resources (FPGA input pins) associated with each GT Transceiver.
# To use these pins an IBUFDS primitive (refclk_ibuf) is
# instantiated in user's design.
# Please refer to the Virtex-7 GT Transceiver User Guide
# (UG) for guidelines regarding clock resource selection.
#
set_property LOC IBUFDS_GTE2_X0Y2 [get_cells refclk_ibuf]

#
# Transceiver instance placement.  This constraint selects the
# transceivers to be used, which also dictates the pinout for the
# transmit and receive differential pairs.  Please refer to the
# Virtex-7 GT Transceiver User Guide (UG) for more information.
#
create_clock -name sys_clk_c -period 10 [get_pins refclk_ibuf/O]
#
# dco_p and dco_n are swapped compared to the FMC ADC schematics
# this is to be coherent in the hdl design


#//A
#//N18;// |OFFSET = IN -1 ns VALID 4.000   BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN AB17 [get_ports {ADC[0]}]
#//R17;// |OFFSET = IN -1 ns VALID 4.000   BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN AA16 [get_ports {ADC[1]}]
#//T18;// |OFFSET = IN -1 ns VALID 4.000   BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN Y13 [get_ports {ADC[2]}]
#//R16;// |OFFSET = IN -1 ns VALID 4.000   BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN AB16 [get_ports {ADC[3]}]
#//U18;// |OFFSET = IN -1 ns VALID 4.000   BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN AA15 [get_ports {ADC[4]}]
#//T17;// |OFFSET = IN -1 ns VALID 4.000  BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN AB15 [get_ports {ADC[5]}]
#//V18;// |OFFSET = IN -1 ns VALID 4.000    BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN Y14 [get_ports {ADC[6]}]
#//V16;// |OFFSET = IN -1 ns VALID 4.000    BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN AA14 [get_ports {ADC[7]}]
#//M11;// |OFFSET = IN -1 ns VALID 4.000    BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN T15 [get_ports {ADC[8]}]
#//R15;// |OFFSET = IN -1 ns VALID 4.000    BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN T14 [get_ports {ADC[9]}]
#//P15;// |OFFSET = IN -1 ns VALID 4.000     BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN T16 [get_ports {ADC[10]}]
#//P14;// |OFFSET = IN -1 ns VALID 4.000   BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN W16 [get_ports {ADC[11]}]
#//U14;// |OFFSET = IN -1 ns VALID 4.000    BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN U16 [get_ports {ADC[12]}]
#//N17;// |OFFSET = IN -1 ns VALID 4.000   BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN W10 [get_ports {ADC[13]}]
#//N12;// |OFFSET = IN - ns VALID 4.000    BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN U15 [get_ports {ADC[14]}]
#//P18;// |OFFSET = IN -0.5 ns  VALID 4.000  BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN W12 [get_ports {ADC[15]}]
#//B
set_property PACKAGE_PIN Y8 [get_ports {ADC1[0]}]
#//R17;// |OFFSET = IN -1 ns VALID 4.000   BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN AA8 [get_ports {ADC1[1]}]
#//T18;// |OFFSET = IN -1 ns VALID 4.000   BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN AA6 [get_ports {ADC1[2]}]
#//R16;// |OFFSET = IN -1 ns VALID 4.000   BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN AB7 [get_ports {ADC1[3]}]
#//U18;// |OFFSET = IN -1 ns VALID 4.000   BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN AB6 [get_ports {ADC1[4]}]
#//T17;// |OFFSET = IN -1 ns VALID 4.000  BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN AB5 [get_ports {ADC1[5]}]
#//V18;// |OFFSET = IN -1 ns VALID 4.000    BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN AA5 [get_ports {ADC1[6]}]
#//V16;// |OFFSET = IN -1 ns VALID 4.000    BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN AB3 [get_ports {ADC1[7]}]
#//M11;// |OFFSET = IN -1 ns VALID 4.000    BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN AB12 [get_ports {ADC1[8]}]
#//R15;// |OFFSET = IN -1 ns VALID 4.000    BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN AA13 [get_ports {ADC1[9]}]
#//P15;// |OFFSET = IN -1 ns VALID 4.000     BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN AA11 [get_ports {ADC1[10]}]
#//P14;// |OFFSET = IN -1 ns VALID 4.000   BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN AB11 [get_ports {ADC1[11]}]
#//U14;// |OFFSET = IN -1 ns VALID 4.000    BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN AA10 [get_ports {ADC1[12]}]
#//N17;// |OFFSET = IN -1 ns VALID 4.000   BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN AB10 [get_ports {ADC1[13]}]
#//N12;// |OFFSET = IN - ns VALID 4.000    BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN Y11 [get_ports {ADC1[14]}]
#//P18;// |OFFSET = IN -0.5 ns  VALID 4.000  BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN AB8 [get_ports {ADC1[15]}]

set_property PACKAGE_PIN W1 [get_ports {ADC2[0]}]
#//R17;// |OFFSET = IN -1 ns VALID 4.000   BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN V2 [get_ports {ADC2[1]}]
#//T18;// |OFFSET = IN -1 ns VALID 4.000   BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN V3 [get_ports {ADC2[2]}]
#//R16;// |OFFSET = IN -1 ns VALID 4.000   BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN U1 [get_ports {ADC2[3]}]
#//U18;// |OFFSET = IN -1 ns VALID 4.000   BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN T1 [get_ports {ADC2[4]}]
#//T17;// |OFFSET = IN -1 ns VALID 4.000  BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN T3 [get_ports {ADC2[5]}]
#//V18;// |OFFSET = IN -1 ns VALID 4.000    BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN U2 [get_ports {ADC2[6]}]
#//V16;// |OFFSET = IN -1 ns VALID 4.000    BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN R3 [get_ports {ADC2[7]}]
#//M11;// |OFFSET = IN -1 ns VALID 4.000    BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN AA3 [get_ports {ADC2[8]}]
#//R15;// |OFFSET = IN -1 ns VALID 4.000    BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN AB2 [get_ports {ADC2[9]}]
#//P15;// |OFFSET = IN -1 ns VALID 4.000     BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN AB1 [get_ports {ADC2[10]}]
#//P14;// |OFFSET = IN -1 ns VALID 4.000   BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN AA1 [get_ports {ADC2[11]}]
#//U14;// |OFFSET = IN -1 ns VALID 4.000    BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN Y2 [get_ports {ADC2[12]}]
#//N17;// |OFFSET = IN -1 ns VALID 4.000   BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN Y1 [get_ports {ADC2[13]}]
#//N12;// |OFFSET = IN - ns VALID 4.000    BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN W2 [get_ports {ADC2[14]}]
#//P18;// |OFFSET = IN -0.5 ns  VALID 4.000  BEFORE CLKFROMADC RISING;
set_property PACKAGE_PIN W4 [get_ports {ADC2[15]}]


#// | SLEW=FAST  | DRIVE = 16  | DIFF_TERM = "FALSE" ;// | OFFSET = IN 1 ns  BEFORE CLKFROMADC RISING ;
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:360
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[0]' has been applied to the port object 'ADC[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC[0]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:361
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[10]' has been applied to the port object 'ADC[10]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC[10]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:362
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[11]' has been applied to the port object 'ADC[11]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC[11]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:363
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[12]' has been applied to the port object 'ADC[12]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC[12]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:364
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[13]' has been applied to the port object 'ADC[13]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC[13]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:365
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[14]' has been applied to the port object 'ADC[14]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC[14]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:366
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[15]' has been applied to the port object 'ADC[15]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC[15]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:367
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[1]' has been applied to the port object 'ADC[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC[1]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:368
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[2]' has been applied to the port object 'ADC[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC[2]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:369
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[3]' has been applied to the port object 'ADC[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC[3]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:370
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[4]' has been applied to the port object 'ADC[4]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC[4]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:371
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[5]' has been applied to the port object 'ADC[5]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC[5]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:372
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[6]' has been applied to the port object 'ADC[6]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC[6]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:373
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[7]' has been applied to the port object 'ADC[7]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC[7]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:374
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[8]' has been applied to the port object 'ADC[8]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC[8]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:375
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[9]' has been applied to the port object 'ADC[9]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC[9]}]

set_property IOSTANDARD LVCMOS33 [get_ports {ADC1[0]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:361
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[10]' has been applied to the port object 'ADC[10]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC1[10]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:362
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[11]' has been applied to the port object 'ADC[11]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC1[11]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:363
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[12]' has been applied to the port object 'ADC[12]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC1[12]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:364
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[13]' has been applied to the port object 'ADC[13]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC1[13]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:365
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[14]' has been applied to the port object 'ADC[14]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC1[14]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:366
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[15]' has been applied to the port object 'ADC[15]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC1[15]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:367
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[1]' has been applied to the port object 'ADC[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC1[1]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:368
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[2]' has been applied to the port object 'ADC[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC1[2]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:369
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[3]' has been applied to the port object 'ADC[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC1[3]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:370
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[4]' has been applied to the port object 'ADC[4]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC1[4]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:371
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[5]' has been applied to the port object 'ADC[5]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC1[5]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:372
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[6]' has been applied to the port object 'ADC[6]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC1[6]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:373
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[7]' has been applied to the port object 'ADC[7]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC1[7]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:374
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[8]' has been applied to the port object 'ADC[8]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC1[8]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:375
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[9]' has been applied to the port object 'ADC[9]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC1[9]}]

set_property IOSTANDARD LVCMOS33 [get_ports {ADC2[0]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:361
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[10]' has been applied to the port object 'ADC[10]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC2[10]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:362
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[11]' has been applied to the port object 'ADC[11]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC2[11]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:363
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[12]' has been applied to the port object 'ADC[12]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC2[12]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:364
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[13]' has been applied to the port object 'ADC[13]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC2[13]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:365
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[14]' has been applied to the port object 'ADC[14]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC2[14]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:366
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[15]' has been applied to the port object 'ADC[15]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC2[15]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:367
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[1]' has been applied to the port object 'ADC[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC2[1]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:368
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[2]' has been applied to the port object 'ADC[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC2[2]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:369
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[3]' has been applied to the port object 'ADC[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC2[3]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:370
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[4]' has been applied to the port object 'ADC[4]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC2[4]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:371
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[5]' has been applied to the port object 'ADC[5]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC2[5]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:372
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[6]' has been applied to the port object 'ADC[6]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC2[6]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:373
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[7]' has been applied to the port object 'ADC[7]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC2[7]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:374
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[8]' has been applied to the port object 'ADC[8]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC2[8]}]
# /home/vladimir/TESTDIFFAC/paac16bit/paac16bit.runs/impl_1/.constrs/pcie_x4_dma.ucf:375
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ADC[9]' has been applied to the port object 'ADC[9]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ADC2[9]}]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets CLK100MHZ]
set_property PACKAGE_PIN W19 [get_ports CLK100MHZ]
set_property IOSTANDARD LVCMOS33 [get_ports CLK100MHZ]
set_property DRIVE 4 [get_ports CLK100MHZ]
set_property SLEW FAST [get_ports CLK100MHZ]
create_clock -period 10.000 -name CLK100MHZ [get_ports CLK100MHZ]


#//  1  CLK_A
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets ADCCLK]
set_property PACKAGE_PIN R4 [get_ports ADCCLK]
set_property IOSTANDARD LVCMOS33 [get_ports ADCCLK]
#//  2  CLK_B
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets ADCCLK1]
set_property PACKAGE_PIN V4 [get_ports ADCCLK1]
set_property IOSTANDARD LVCMOS33 [get_ports ADCCLK1]
#//  3 CLK_C
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets ADCCLK2]
set_property PACKAGE_PIN V13 [get_ports ADCCLK2]
set_property IOSTANDARD LVCMOS33 [get_ports ADCCLK2]

set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE YES [current_design]
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]