# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/vladimir/TESTDIFFAC/cernv1/cernv1.srcs/sources_1/ip/v6_eb_fifo_counted_resized/v6_eb_fifo_counted_resized.xci
# IP: The module: 'v6_eb_fifo_counted_resized' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vladimir/TESTDIFFAC/cernv1/cernv1.srcs/sources_1/ip/v6_eb_fifo_counted_resized/v6_eb_fifo_counted_resized/v6_eb_fifo_counted_resized_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'v6_eb_fifo_counted_resized'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/vladimir/TESTDIFFAC/cernv1/cernv1.srcs/sources_1/ip/v6_eb_fifo_counted_resized/v6_eb_fifo_counted_resized/v6_eb_fifo_counted_resized.xdc
# XDC: The top module name and the constraint reference have the same name: 'v6_eb_fifo_counted_resized'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/vladimir/TESTDIFFAC/cernv1/cernv1.srcs/sources_1/ip/v6_eb_fifo_counted_resized/v6_eb_fifo_counted_resized_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'v6_eb_fifo_counted_resized'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/vladimir/TESTDIFFAC/cernv1/cernv1.srcs/sources_1/ip/v6_eb_fifo_counted_resized/v6_eb_fifo_counted_resized.xci
# IP: The module: 'v6_eb_fifo_counted_resized' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vladimir/TESTDIFFAC/cernv1/cernv1.srcs/sources_1/ip/v6_eb_fifo_counted_resized/v6_eb_fifo_counted_resized/v6_eb_fifo_counted_resized_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'v6_eb_fifo_counted_resized'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/vladimir/TESTDIFFAC/cernv1/cernv1.srcs/sources_1/ip/v6_eb_fifo_counted_resized/v6_eb_fifo_counted_resized/v6_eb_fifo_counted_resized.xdc
# XDC: The top module name and the constraint reference have the same name: 'v6_eb_fifo_counted_resized'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/vladimir/TESTDIFFAC/cernv1/cernv1.srcs/sources_1/ip/v6_eb_fifo_counted_resized/v6_eb_fifo_counted_resized_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'v6_eb_fifo_counted_resized'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
